# Configuração mínima do Jekyll para GitHub Pages
title: Editorial Norte
email: seu-contatoindesbrasil@gmail.com
description: "Site de notícias e matérias do Editorial Norte"
baseurl: "" # deixe vazio
url: "https://mercado-portal.github.io" # seu domínio GitHub Pages
theme: minima

# Exibir posts completos no feed
show_excerpts: true

# Configuração de build
markdown: kramdown
plugins:
  - jekyll-feed
